name: detekt
on: [ pull_request]
jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2
      - name: "look around"
        run : "ls -a"
      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.19.0-RC1
#         TODO restore when done testing
#        with:
#          args: --fail-fast --config detekt.yml